### ISSUE TITLE
Documentation only exists in In-Game Wiki, which has no 1.10 version

### ISSUE THREAD

**Issue by LiaungYip** [MineMaarten/Signals#14]
This makes it hard to look up reference information for the mod.

Possible fixes:
- Update In Game Wiki to 1.10
- Host documentation on external website.

**Comment by LiaungYip** [comment]
As a temporary workaround, I've reformatted the In Game Wiki information for the web, and I'm hosting a copy of it at https://fleeting.penwatch.net/signals/ .

This is a static copy, so it won't track any updates to the upstream documentation.

**Comment by MineMaarten** [comment]
In-Game Wiki mod for MC 1.9.4 should be compatible with MC 1.10. I've updated the 'supported versions' in the curse description so it's less confusing.

Still awesome work hosting the info externally! The reason I'm not doing it myself is because it's a lot of work to manage one wiki, let alone keeping two up to date.

**Comment by LiaungYip** [comment]
Reformatting the in-game wiki information for the web wasn't too hard. I could probably write a bit of Python to automate the conversion and upload to a web host.

Would that be useful and appreciated?

**Comment by LiaungYip** [comment]
Just a quick note:

There's now a (improved) copy of the documentation, as a Hugo site, at https://github.com/LiaungYip/signals-docs (and deployed to https://fleeting.penwatch.net/signals/ ).

Mainly  this is because I'm developing a new Hugo theme for documentation websites, and I needed some documentation pages to test it on. :)
