### ISSUE TITLE
Railcraft Trains

### ISSUE THREAD

**Issue by Tyrantin** [MineMaarten/Signals#17]
When Doing a more complex Rail system, Trains from Railcraft are not routing correctly. I have 3 Stations with multiple Lines within them. The Stations are a small part of the Problem. The main Problem is the "Junction" of all 3 Extensions. The Trains Refuse to take the Path intended. Please see Images below!

![2017-02-11_06 25 20](https://cloud.githubusercontent.com/assets/8041616/22853448/8a5417d0-f024-11e6-8678-f0e17dc46b30.png)

![2017-02-11_06 27 13](https://cloud.githubusercontent.com/assets/8041616/22853450/92abc040-f024-11e6-8d6c-d7594a1cd463.png)

**Comment by MineMaarten** [comment]
Sorry for the late response.

From what you tell I can only think of that the rail network was not fully chunkloaded?

And by looking at what you were trying to do, you could simply make destination A through C be right after the intersection, so that the pathfinder does not need to look at the entire (unloaded) rail network. 

Also try sneak-right-clicking the Rail Configurator and the signals should be connected with lines. and try to look at the Rail Network Controller. It should show you some info about the paths being taken.

**Comment by MineMaarten** [comment]
This version should probably resolve this
https://minecraft.curseforge.com/projects/signals/files/2552172
If not, let me know.
